---
version: "3.8"
services:
  opsbox-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    image: opsbox-api:compose
    # ports:
    #   - "8001:8001"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/app/data/init:/docker-entrypoint-initdb.d

  opsbox-web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    image: opsbox-web:compose
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - opsbox-api

volumes:
  postgres_data:
