apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: opsbox
  source:
    repoURL: https://github.com/kieukhang185/opsbox.git
    targetRevision: dev
    path: ./gitops/config/opsbox-configmap.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated: {}
