global:
  imageRegistry: ghcr.io
  rabbitmq:
  security:
    allowInsecureImages: true
auth:
  username: opsbox
  password: opsbox
image:
  registry: ghcr.io
  repository: kieukhang185/rabbitmq
  tag: "4.1.3"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:   # need to a bit large for deplotyment to faster
    cpu: 1
    memory: 1Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels:
      release: monitoring # match prometheus-operator release name

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""
