---
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "teams"
      group_by: ["alertname", "job", "namespace"]
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 3h
    receivers:
      - name: "teams"
        webhook_configs:
          - url: ""
            send_resolved: true
